name: Test Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint go code
        uses: golangci/golangci-lint-action@v3
  lint-files:
    name: Lint other files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint other files
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: false
  build-code:
    name: Test code build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up GO
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Run GoReleaser without release
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: build --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}